name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Headless Pygame
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          echo "SDL_VIDEODRIVER=dummy" >> $GITHUB_ENV

      - name: Lint
        run: python -m pre_commit run -a || true

      - name: Tests
        run: xvfb-run -a pytest -q
